### ISSUE TITLE
Not able to get required accuracy

### ISSUE THREAD

**Issue by tapadeep** [AnryYang/PANE#1]
Using the Cora dataset from  [https://github.com/mengzaiqiao/CAN/tree/master/data](url), I can't seem to get good accuracy (with dim=128) even with many iterations. Can you mention the hyper-params used in the reported paper?

**Comment by AnryYang** [comment]
> Using the Cora dataset from [https://github.com/mengzaiqiao/CAN/tree/master/data](url), I can't seem to get good accuracy (with dim=128) even with many iterations. Can you mention the hyper-params used in the reported paper?

Please collect the data from here http://www4.comp.polyu.edu.hk/~jiemshi/datasets.html. Follow the settings mentioned in the paper and use the evaluator in this repository. Thanks.
